### PR TITLE
Fix: Update watch paths when renaming directories with sub-watches on Windows 

### LINKED ISSUE #243: Creating a file inside a folder created using windows explorer generates events for the wrong dir
Before reporting an issue, please ensure you are using the latest release of fsnotify.

### Which operating system (GOOS) and version are you using?
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.14393 N/A Build 14393
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free

### Please describe the issue that occurred.
Creating a file inside a folder created through windows explorer triggers an event for the `New folder` name, not the one actually chosen.

### Are you able to reproduce the issue? Please provide steps to reproduce and a code sample if possible.

- Run this program:
- Create a new folder in the watched directory using windows explorer (it works if you just use powershell). Give it some name.
- Create a new folder or file or folder inside the folder you just created.
- You should see the error attached below

```
package main

import (
	"fmt"
	"log"

	"github.com/fsnotify/fsnotify"
)

func main() {
	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		log.Fatal(err)
	}

	err = watcher.Add(".")
	if err != nil {
		log.Fatal(err)
	}

	for ev := range watcher.Events {
		fmt.Printf("got event %+v\n", ev)
		if ev.Op == fsnotify.Create {
			err = watcher.Add(ev.Name)
			fmt.Println("adding ", ev.Name, "to watch list")
			if err != nil {
				log.Fatal(err)
			}
		}
	}
}
```

You should see something like:
```
# using windows explorer, click on "New Folder"
got event "New folder": CREATE
adding  New folder to watch list
# pick the name abc for the folder
got event "New folder": RENAME
got event "abc": CREATE
adding  abc to watch list
# create another folder inside abc and you'll see the issue. It reports the new folder being created inside "New folder", not the chosen name "abc"
got event "New folder\\New folder": CREATE
adding  New folder\New folder to watch list
# naturally, it fails because the folder doesn't exist so it can't be watched
2018/04/20 17:26:42 GetFileAttributes: The system cannot find the path specified.
exit status 1
```

If I run the program again and create a file inside `abc`, the events are triggered as expected.

### LINKED ISSUE #259: Renaming folder which already added to watch
### Operating system and version.

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free

### Here is the description of the issue that occurred.

While creating new folder if I rename that folder to any custome name and than if I will create any files into that folder  at that time watcher try to find that files into old folder path which was created by system not on the given custome name

1) Output when I first create folder with custome name.
It adds both the folder path into watches
creatrenamedir
 
2) When I create any file into renamed folder it try to finds that file into old name folder.
creatrenamedir2

I also tried removing old directory path from watcher but it not removing it actually..!

### Are you able to reproduce the issue? Please provide steps to reproduce and a code sample if possible.

1. Add a directory to watch
2. Create new folder in that directory by right clicking in windows explorer and give it name you like
3. When watcher fires create event then add newly created directory to watch

### PR DESCRIPTION
**Pull request by arnegroskurth**
#### What does this pull request do?

Fixes #259
Fixes #243

### CODE REVIEW

File: windows.go [hunk 1]
```diff
@@ -464,6 +465,17 @@ func (w *Watcher) readEvents() {
...
 				watch.rename = name
 			case syscall.FILE_ACTION_RENAMED_NEW_NAME:
+
+				// update saved path of all sub-watches
+				oldFullName := filepath.Join(watch.path, watch.rename)
+				for _, watchMap := range w.watches {
+					for _, otherWatch := range watchMap {
+						if strings.HasPrefix(otherWatch.path, oldFullName) {
+							otherWatch.path = filepath.Join(fullname, strings.TrimPrefix(otherWatch.path, oldFullName))
+						}
```
Comment (nathany) [inline windows.go:475]: I think you need some locking when operating on the map.

**Review by nathany — COMMENTED** [review]
Thanks for the contribution.

File: integration_test.go [hunk 2]
```diff
@@ -1226,6 +1227,55 @@ func TestRemoveWithClose(t *testing.T) {
...
+			if !ok {
+				return
+			}
+			events = append(events, event)
+		}
+	}()
+
+	addWatch(t, watcher, testDir)
+
+	if err := os.Mkdir(testDir+"/dir", 0o775); err != nil {
```
Comment (mattn) [inline integration_test.go:1251]: Please use filepath.Join and below.

**Review by arp242 — APPROVED** [review]
